services:
  api:
    build: .
    container_name: ias-api
    environment:
      API_PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
    command: npm run start:dev
  
  postgres:
    image: postgres:16
    container_name: ias-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 148787
      POSTGRES_DB: ias_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: